window.allHoldingsDetail = [
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "DUK",
        "description":  "DUKE ENERGY CORP NEW",
        "quantity":  "1",
        "price":  "120.95",
        "priceChange":  "-3.36",
        "marketValue":  "$120.95",
        "marketValueNumber":  120.95,
        "dayChange":  "-$3.36",
        "dayChangePct":  "-2.7%",
        "costBasis":  "$111.55",
        "gain":  "$9.40",
        "gainNumber":  9.4,
        "gainPct":  "8.43%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "EXEL",
        "description":  "EXELIXIS INC",
        "quantity":  "2",
        "price":  "50.13",
        "priceChange":  "-0.97",
        "marketValue":  "$100.26",
        "marketValueNumber":  100.26,
        "dayChange":  "-$1.94",
        "dayChangePct":  "-1.9%",
        "costBasis":  "$43.73",
        "gain":  "$56.53",
        "gainNumber":  56.53,
        "gainPct":  "129.27%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "D",
        "description":  "DOMINION ENERGY INC",
        "quantity":  "1",
        "price":  "61.73",
        "priceChange":  "-1.24",
        "marketValue":  "$61.73",
        "marketValueNumber":  61.73,
        "dayChange":  "-$1.24",
        "dayChangePct":  "-1.97%",
        "costBasis":  "$55.72",
        "gain":  "$6.01",
        "gainNumber":  6.01,
        "gainPct":  "10.79%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "AMD",
        "description":  "ADVANCED MICRO DEVIC",
        "quantity":  "1",
        "price":  "424.10",
        "priceChange":  "-25.60",
        "marketValue":  "$424.10",
        "marketValueNumber":  424.1,
        "dayChange":  "-$25.60",
        "dayChangePct":  "-5.69%",
        "costBasis":  "$121.53",
        "gain":  "$302.57",
        "gainNumber":  302.57,
        "gainPct":  "248.97%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "AMZN",
        "description":  "AMAZON.COM INC",
        "quantity":  "1",
        "price":  "264.14",
        "priceChange":  "-3.08",
        "marketValue":  "$264.14",
        "marketValueNumber":  264.14,
        "dayChange":  "-$3.08",
        "dayChangePct":  "-1.15%",
        "costBasis":  "$176.74",
        "gain":  "$87.40",
        "gainNumber":  87.4,
        "gainPct":  "49.45%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "GOOGL",
        "description":  "ALPHABET INC CLASS A",
        "quantity":  "1",
        "price":  "396.78",
        "priceChange":  "-4.29",
        "marketValue":  "$396.78",
        "marketValueNumber":  396.78,
        "dayChange":  "-$4.29",
        "dayChangePct":  "-1.07%",
        "costBasis":  "$163.33",
        "gain":  "$233.45",
        "gainNumber":  233.45,
        "gainPct":  "142.93%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "MSFT",
        "description":  "MICROSOFT CORP",
        "quantity":  "1",
        "price":  "421.92",
        "priceChange":  "12.49",
        "marketValue":  "$421.92",
        "marketValueNumber":  421.92,
        "dayChange":  "$12.49",
        "dayChangePct":  "3.05%",
        "costBasis":  "$408.02",
        "gain":  "$13.90",
        "gainNumber":  13.9,
        "gainPct":  "3.41%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "MXL",
        "description":  "MAXLINEAR INC CLASS CLASS A",
        "quantity":  "4",
        "price":  "92.34",
        "priceChange":  "3.56",
        "marketValue":  "$369.36",
        "marketValueNumber":  369.36,
        "dayChange":  "$14.24",
        "dayChangePct":  "4.01%",
        "costBasis":  "$174.51",
        "gain":  "$194.85",
        "gainNumber":  194.85,
        "gainPct":  "111.66%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "LTRX",
        "description":  "LANTRONIX INC",
        "quantity":  "6",
        "price":  "6.27",
        "priceChange":  "-0.18",
        "marketValue":  "$37.62",
        "marketValueNumber":  37.62,
        "dayChange":  "-$1.08",
        "dayChangePct":  "-2.79%",
        "costBasis":  "$29.35",
        "gain":  "$8.27",
        "gainNumber":  8.27,
        "gainPct":  "28.18%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "HLX",
        "description":  "HELIX ENERGY SOLUTIONS G",
        "quantity":  "4",
        "price":  "10.05",
        "priceChange":  "-0.09",
        "marketValue":  "$40.20",
        "marketValueNumber":  40.2,
        "dayChange":  "-$0.36",
        "dayChangePct":  "-0.89%",
        "costBasis":  "$41.52",
        "gain":  "-$1.32",
        "gainNumber":  -1.32,
        "gainPct":  "-3.18%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "INTC",
        "description":  "INTEL CORP",
        "quantity":  "3",
        "price":  "108.77",
        "priceChange":  "-7.16",
        "marketValue":  "$326.31",
        "marketValueNumber":  326.31,
        "dayChange":  "-$21.48",
        "dayChangePct":  "-6.18%",
        "costBasis":  "$101.43",
        "gain":  "$224.88",
        "gainNumber":  224.88,
        "gainPct":  "221.71%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "UBER",
        "description":  "UBER TECHNOLOGIES INC COM",
        "quantity":  "1",
        "price":  "$75.09",
        "priceChange":  "+$0.40",
        "marketValue":  "$75.09",
        "marketValueNumber":  75.09,
        "dayChange":  "+$0.40",
        "dayChangePct":  "+0.53%",
        "costBasis":  "$84.76",
        "gain":  "-$9.67",
        "gainNumber":  -9.67,
        "gainPct":  "-11.41%",
        "accountWeight":  "2.40%",
        "averageCostBasis":  "$84.76",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "VMC",
        "description":  "VULCAN MATERIALS CO",
        "quantity":  "0.007",
        "price":  "$267.83",
        "priceChange":  "-$7.26",
        "marketValue":  "$1.87",
        "marketValueNumber":  1.87,
        "dayChange":  "-$0.06",
        "dayChangePct":  "-2.64%",
        "costBasis":  "$1.97",
        "gain":  "-$0.10",
        "gainNumber":  -0.1,
        "gainPct":  "-4.84%",
        "accountWeight":  "0.06%",
        "averageCostBasis":  "$281.43",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "TT",
        "description":  "TRANE TECHNOLOGIES PLC COM USD1",
        "quantity":  "0.004",
        "price":  "$466.60",
        "priceChange":  "-$15.07",
        "marketValue":  "$1.86",
        "marketValueNumber":  1.86,
        "dayChange":  "-$0.07",
        "dayChangePct":  "-3.13%",
        "costBasis":  "$1.64",
        "gain":  "+$0.22",
        "gainNumber":  0.22,
        "gainPct":  "+13.80%",
        "accountWeight":  "0.06%",
        "averageCostBasis":  "$410.00",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "SO",
        "description":  "SOUTHERN CO",
        "quantity":  "0.022",
        "price":  "$91.79",
        "priceChange":  "-$1.13",
        "marketValue":  "$2.01",
        "marketValueNumber":  2.01,
        "dayChange":  "-$0.03",
        "dayChangePct":  "-1.22%",
        "costBasis":  "$2.00",
        "gain":  "+$0.01",
        "gainNumber":  0.01,
        "gainPct":  "+0.96%",
        "accountWeight":  "0.06%",
        "averageCostBasis":  "$90.91",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "TSM",
        "description":  "TAIWAN SEMICONDUCTOR MANUFACTURING SPON ADS EACH REP 5 ORD TWD10",
        "quantity":  "0.007",
        "price":  "$404.35",
        "priceChange":  "-$13.37",
        "marketValue":  "$2.83",
        "marketValueNumber":  2.83,
        "dayChange":  "-$0.10",
        "dayChangePct":  "-3.21%",
        "costBasis":  "$1.93",
        "gain":  "+$0.90",
        "gainNumber":  0.9,
        "gainPct":  "+46.65%",
        "accountWeight":  "0.09%",
        "averageCostBasis":  "$275.71",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "VRT",
        "description":  "VERTIV HOLDINGS CO COM CL A",
        "quantity":  "0.012",
        "price":  "$370.94",
        "priceChange":  "-$5.29",
        "marketValue":  "$4.45",
        "marketValueNumber":  4.45,
        "dayChange":  "-$0.07",
        "dayChangePct":  "-1.41%",
        "costBasis":  "$1.93",
        "gain":  "+$2.52",
        "gainNumber":  2.52,
        "gainPct":  "+130.63%",
        "accountWeight":  "0.14%",
        "averageCostBasis":  "$160.83",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "Pending activity",
        "description":  "",
        "quantity":  "",
        "price":  "",
        "priceChange":  "",
        "marketValue":  "$100.00",
        "marketValueNumber":  100,
        "dayChange":  "",
        "dayChangePct":  "",
        "costBasis":  "",
        "gain":  "",
        "gainNumber":  null,
        "gainPct":  "",
        "accountWeight":  "",
        "averageCostBasis":  null,
        "assetType":  "Other",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "AI",
        "description":  "C3 AI INC CLASS A",
        "quantity":  "3",
        "price":  "8.65",
        "priceChange":  "-0.38",
        "marketValue":  "$25.95",
        "marketValueNumber":  25.95,
        "dayChange":  "-$1.14",
        "dayChangePct":  "-4.21%",
        "costBasis":  "$81.35",
        "gain":  "-$55.40",
        "gainNumber":  -55.4,
        "gainPct":  "-68.1%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "XYL",
        "description":  "XYLEM INC COM USD0.01",
        "quantity":  "0.014",
        "price":  "$108.12",
        "priceChange":  "-$1.32",
        "marketValue":  "$1.51",
        "marketValueNumber":  1.51,
        "dayChange":  "-$0.02",
        "dayChangePct":  "-1.21%",
        "costBasis":  "$1.95",
        "gain":  "-$0.44",
        "gainNumber":  -0.44,
        "gainPct":  "-22.38%",
        "accountWeight":  "0.05%",
        "averageCostBasis":  "$139.29",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "VTI",
        "description":  "VANGUARD INDEX FDS VANGUARD TOTAL STK MKT ETF",
        "quantity":  "0.545",
        "price":  "$362.74",
        "priceChange":  "-$4.66",
        "marketValue":  "$197.69",
        "marketValueNumber":  197.69,
        "dayChange":  "-$2.54",
        "dayChangePct":  "-1.27%",
        "costBasis":  "$179.95",
        "gain":  "+$17.74",
        "gainNumber":  17.74,
        "gainPct":  "+9.86%",
        "accountWeight":  "6.32%",
        "averageCostBasis":  "$330.18",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "XEL",
        "description":  "XCEL ENERGY INC COM USD2.5",
        "quantity":  "0.024",
        "price":  "$77.92",
        "priceChange":  "-$2.11",
        "marketValue":  "$1.87",
        "marketValueNumber":  1.87,
        "dayChange":  "-$0.06",
        "dayChangePct":  "-2.64%",
        "costBasis":  "$1.94",
        "gain":  "-$0.07",
        "gainNumber":  -0.07,
        "gainPct":  "-3.61%",
        "accountWeight":  "0.06%",
        "averageCostBasis":  "$80.83",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "NVDA",
        "description":  "NVIDIA CORP",
        "quantity":  "2",
        "price":  "225.32",
        "priceChange":  "-10.42",
        "marketValue":  "$450.64",
        "marketValueNumber":  450.64,
        "dayChange":  "-$20.84",
        "dayChangePct":  "-4.42%",
        "costBasis":  "$248.52",
        "gain":  "$202.12",
        "gainNumber":  202.12,
        "gainPct":  "81.33%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "ROBT",
        "description":  "FIRST TRUST NASDAQ ARTIFICIAL INTELLIGENCE AND ROBOTICS ETF",
        "quantity":  "5",
        "price":  "53.68",
        "priceChange":  "-0.75",
        "marketValue":  "$268.40",
        "marketValueNumber":  268.4,
        "dayChange":  "-$3.75",
        "dayChangePct":  "-1.38%",
        "costBasis":  "$250.83",
        "gain":  "$17.57",
        "gainNumber":  17.57,
        "gainPct":  "7%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "ETFs \u0026 Closed End Funds",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "SLV",
        "description":  "ISHARES SILVER TRUST",
        "quantity":  "2",
        "price":  "69.04",
        "priceChange":  "-6.47",
        "marketValue":  "$138.08",
        "marketValueNumber":  138.08,
        "dayChange":  "-$12.94",
        "dayChangePct":  "-8.57%",
        "costBasis":  "$90.45",
        "gain":  "$47.63",
        "gainNumber":  47.63,
        "gainPct":  "52.66%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "ETFs \u0026 Closed End Funds",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "LRNZ",
        "description":  "TRUESHARES TECHNOLOGY, AI AND DEEP LEARNING ETF",
        "quantity":  "2",
        "price":  "50.4847",
        "priceChange":  "-0.9364",
        "marketValue":  "$100.97",
        "marketValueNumber":  100.97,
        "dayChange":  "-$1.87",
        "dayChangePct":  "-1.82%",
        "costBasis":  "$68.68",
        "gain":  "$32.29",
        "gainNumber":  32.29,
        "gainPct":  "47.02%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "ETFs \u0026 Closed End Funds",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "DRAM",
        "description":  "ROUNDHILL MEMORY ETF",
        "quantity":  "1",
        "price":  "51.10",
        "priceChange":  "-2.69",
        "marketValue":  "$51.10",
        "marketValueNumber":  51.1,
        "dayChange":  "-$2.69",
        "dayChangePct":  "-5%",
        "costBasis":  "$53.94",
        "gain":  "-$2.84",
        "gainNumber":  -2.84,
        "gainPct":  "-5.27%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "ETFs \u0026 Closed End Funds",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "IBIT",
        "description":  "ISHARES BITCOIN TRUST ETF",
        "quantity":  "1",
        "price":  "44.82",
        "priceChange":  "-1.35",
        "marketValue":  "$44.82",
        "marketValueNumber":  44.82,
        "dayChange":  "-$1.35",
        "dayChangePct":  "-2.92%",
        "costBasis":  "$40.53",
        "gain":  "$4.29",
        "gainNumber":  4.29,
        "gainPct":  "10.58%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "ETFs \u0026 Closed End Funds",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "SPRX",
        "description":  "SPEAR ALPHA ETF",
        "quantity":  "2",
        "price":  "48.15",
        "priceChange":  "-2.26",
        "marketValue":  "$96.30",
        "marketValueNumber":  96.3,
        "dayChange":  "-$4.52",
        "dayChangePct":  "-4.48%",
        "costBasis":  "$47.86",
        "gain":  "$48.44",
        "gainNumber":  48.44,
        "gainPct":  "101.21%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "ETFs \u0026 Closed End Funds",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "XT",
        "description":  "ISHARES FUTURE EXPONENTIAL TECHNOLOGIESETF",
        "quantity":  "2",
        "price":  "79.12",
        "priceChange":  "-1.65",
        "marketValue":  "$158.24",
        "marketValueNumber":  158.24,
        "dayChange":  "-$3.30",
        "dayChangePct":  "-2.04%",
        "costBasis":  "$109.18",
        "gain":  "$49.06",
        "gainNumber":  49.06,
        "gainPct":  "44.93%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "ETFs \u0026 Closed End Funds",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "Cash \u0026 Cash Investments",
        "description":  "--",
        "quantity":  "--",
        "price":  "--",
        "priceChange":  "--",
        "marketValue":  "$81.64",
        "marketValueNumber":  81.64,
        "dayChange":  "$0.00",
        "dayChangePct":  "0%",
        "costBasis":  "--",
        "gain":  "--",
        "gainNumber":  null,
        "gainPct":  "--",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Cash and Money Market",
        "reinvest":  "--",
        "reinvestCapitalGains":  "--"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "XLF",
        "description":  "STATE STREET FINANCIAL SELECT SECTOR SPDR ETF",
        "quantity":  "1",
        "price":  "51.10",
        "priceChange":  "-0.19",
        "marketValue":  "$51.10",
        "marketValueNumber":  51.1,
        "dayChange":  "-$0.19",
        "dayChangePct":  "-0.37%",
        "costBasis":  "$49.17",
        "gain":  "$1.93",
        "gainNumber":  1.93,
        "gainPct":  "3.93%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "ETFs \u0026 Closed End Funds",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "WTAI",
        "description":  "WISDOMTREE ARTIFICIAL INTELLIGENCE AND INNOVATION FUND",
        "quantity":  "3",
        "price":  "40.37",
        "priceChange":  "-1.17",
        "marketValue":  "$121.11",
        "marketValueNumber":  121.11,
        "dayChange":  "-$3.51",
        "dayChangePct":  "-2.82%",
        "costBasis":  "$68.38",
        "gain":  "$52.73",
        "gainNumber":  52.73,
        "gainPct":  "77.11%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "ETFs \u0026 Closed End Funds",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "XLE",
        "description":  "STATE STREET ENERGY SELECT SECTOR SPDR ETF",
        "quantity":  "4",
        "price":  "59.44",
        "priceChange":  "1.37",
        "marketValue":  "$237.76",
        "marketValueNumber":  237.76,
        "dayChange":  "$5.48",
        "dayChangePct":  "2.36%",
        "costBasis":  "$181.82",
        "gain":  "$55.94",
        "gainNumber":  55.94,
        "gainPct":  "30.77%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "ETFs \u0026 Closed End Funds",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "TEM",
        "description":  "TEMPUS AI INC CLASS CLASS A",
        "quantity":  "2",
        "price":  "43.93",
        "priceChange":  "-1.55",
        "marketValue":  "$87.86",
        "marketValueNumber":  87.86,
        "dayChange":  "-$3.10",
        "dayChangePct":  "-3.41%",
        "costBasis":  "$142.54",
        "gain":  "-$54.68",
        "gainNumber":  -54.68,
        "gainPct":  "-38.36%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "U",
        "description":  "UNITY SOFTWARE INC",
        "quantity":  "2",
        "price":  "27.16",
        "priceChange":  "-0.12",
        "marketValue":  "$54.32",
        "marketValueNumber":  54.32,
        "dayChange":  "-$0.24",
        "dayChangePct":  "-0.44%",
        "costBasis":  "$50.92",
        "gain":  "$3.40",
        "gainNumber":  3.4,
        "gainPct":  "6.68%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "SYM",
        "description":  "SYMBOTIC INC CLASS A",
        "quantity":  "2",
        "price":  "47.32",
        "priceChange":  "-2.83",
        "marketValue":  "$94.64",
        "marketValueNumber":  94.64,
        "dayChange":  "-$5.66",
        "dayChangePct":  "-5.64%",
        "costBasis":  "$79.98",
        "gain":  "$14.66",
        "gainNumber":  14.66,
        "gainPct":  "18.33%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "PATH",
        "description":  "UIPATH INC CLASS CLASS A",
        "quantity":  "2",
        "price":  "10.27",
        "priceChange":  "0.60",
        "marketValue":  "$20.54",
        "marketValueNumber":  20.54,
        "dayChange":  "$1.20",
        "dayChangePct":  "6.2%",
        "costBasis":  "$41.67",
        "gain":  "-$21.13",
        "gainNumber":  -21.13,
        "gainPct":  "-50.71%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "SOUN",
        "description":  "SOUNDHOUND AI INC CLASS A",
        "quantity":  "10",
        "price":  "8.41",
        "priceChange":  "-0.11",
        "marketValue":  "$84.10",
        "marketValueNumber":  84.1,
        "dayChange":  "-$1.10",
        "dayChangePct":  "-1.29%",
        "costBasis":  "$21.35",
        "gain":  "$62.75",
        "gainNumber":  62.75,
        "gainPct":  "293.91%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "UPST",
        "description":  "UPSTART HLDGS INC",
        "quantity":  "1",
        "price":  "29.51",
        "priceChange":  "-0.20",
        "marketValue":  "$29.51",
        "marketValueNumber":  29.51,
        "dayChange":  "-$0.20",
        "dayChangePct":  "-0.67%",
        "costBasis":  "$24.52",
        "gain":  "$4.99",
        "gainNumber":  4.99,
        "gainPct":  "20.35%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "Equity",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "BTX",
        "description":  "BLACKROCK TECH AND PRIVA",
        "quantity":  "20",
        "price":  "8.59",
        "priceChange":  "-0.24",
        "marketValue":  "$171.80",
        "marketValueNumber":  171.8,
        "dayChange":  "-$4.80",
        "dayChangePct":  "-2.72%",
        "costBasis":  "$148.30",
        "gain":  "$23.50",
        "gainNumber":  23.5,
        "gainPct":  "15.85%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "ETFs \u0026 Closed End Funds",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "CHAT",
        "description":  "ROUNDHILL GENERATIVE AI \u0026 TECHNOLOGY ETF",
        "quantity":  "20",
        "price":  "85.49",
        "priceChange":  "-3.29",
        "marketValue":  "$1,709.80",
        "marketValueNumber":  1709.8,
        "dayChange":  "-$65.80",
        "dayChangePct":  "-3.71%",
        "costBasis":  "$1,129.53",
        "gain":  "$580.27",
        "gainNumber":  580.27,
        "gainPct":  "51.37%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "ETFs \u0026 Closed End Funds",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "BITC",
        "description":  "BITWISE TRENDWISE BITCOIN AND TREASURIES ROTATION STRATEGY ETF",
        "quantity":  "1",
        "price":  "40.14",
        "priceChange":  "-1.2128",
        "marketValue":  "$40.14",
        "marketValueNumber":  40.14,
        "dayChange":  "-$1.21",
        "dayChangePct":  "-2.93%",
        "costBasis":  "$72.87",
        "gain":  "-$32.73",
        "gainNumber":  -32.73,
        "gainPct":  "-44.92%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "ETFs \u0026 Closed End Funds",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "AIO",
        "description":  "VIRTUS ARTIFICIAL INTELL",
        "quantity":  "5",
        "price":  "26.21",
        "priceChange":  "-0.39",
        "marketValue":  "$131.05",
        "marketValueNumber":  131.05,
        "dayChange":  "-$1.95",
        "dayChangePct":  "-1.47%",
        "costBasis":  "$122.56",
        "gain":  "$8.49",
        "gainNumber":  8.49,
        "gainPct":  "6.93%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "ETFs \u0026 Closed End Funds",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "thinkorswim",
        "accountName":  "Individual",
        "symbol":  "ARTY",
        "description":  "ISHARES FUTURE AI \u0026 TECHETF",
        "quantity":  "2",
        "price":  "65.80",
        "priceChange":  "-2.77",
        "marketValue":  "$131.60",
        "marketValueNumber":  131.6,
        "dayChange":  "-$5.54",
        "dayChangePct":  "-4.04%",
        "costBasis":  "$66.19",
        "gain":  "$65.41",
        "gainNumber":  65.41,
        "gainPct":  "98.82%",
        "accountWeight":  "",
        "averageCostBasis":  "",
        "assetType":  "ETFs \u0026 Closed End Funds",
        "reinvest":  "No",
        "reinvestCapitalGains":  "N/A"
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "DRAM",
        "description":  "ROUNDHILL ETF TRUST MEMORY ETF",
        "quantity":  "5.176",
        "price":  "$51.10",
        "priceChange":  "-$2.69",
        "marketValue":  "$264.49",
        "marketValueNumber":  264.49,
        "dayChange":  "-$13.93",
        "dayChangePct":  "-5.01%",
        "costBasis":  "$280.00",
        "gain":  "-$15.51",
        "gainNumber":  -15.51,
        "gainPct":  "-5.54%",
        "accountWeight":  "8.46%",
        "averageCostBasis":  "$54.10",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "DUK",
        "description":  "DUKE ENERGY CORP NEW COM NEW ISIN #US26441C2044 SEDOL #B7JZSK0",
        "quantity":  "0.016",
        "price":  "$120.95",
        "priceChange":  "-$2.295",
        "marketValue":  "$1.93",
        "marketValueNumber":  1.93,
        "dayChange":  "-$0.04",
        "dayChangePct":  "-1.87%",
        "costBasis":  "$1.98",
        "gain":  "-$0.05",
        "gainNumber":  -0.05,
        "gainPct":  "-2.27%",
        "accountWeight":  "0.06%",
        "averageCostBasis":  "$123.75",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "DLR",
        "description":  "DIGITAL REALTY TRUST INC",
        "quantity":  "0.012",
        "price":  "$188.51",
        "priceChange":  "-$4.33",
        "marketValue":  "$2.26",
        "marketValueNumber":  2.26,
        "dayChange":  "-$0.06",
        "dayChangePct":  "-2.25%",
        "costBasis":  "$1.89",
        "gain":  "+$0.37",
        "gainNumber":  0.37,
        "gainPct":  "+19.68%",
        "accountWeight":  "0.07%",
        "averageCostBasis":  "$157.50",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "CRWD",
        "description":  "CROWDSTRIKE HLDGS INC CL A",
        "quantity":  "0.003",
        "price":  "$594.08",
        "priceChange":  "+$14.13",
        "marketValue":  "$1.78",
        "marketValueNumber":  1.78,
        "dayChange":  "+$0.04",
        "dayChangePct":  "+2.43%",
        "costBasis":  "$1.56",
        "gain":  "+$0.22",
        "gainNumber":  0.22,
        "gainPct":  "+14.24%",
        "accountWeight":  "0.06%",
        "averageCostBasis":  "$520.00",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "D",
        "description":  "DOMINION ENERGY INC COM",
        "quantity":  "0.032",
        "price":  "$61.73",
        "priceChange":  "-$1.24",
        "marketValue":  "$1.97",
        "marketValueNumber":  1.97,
        "dayChange":  "-$0.04",
        "dayChangePct":  "-1.97%",
        "costBasis":  "$1.97",
        "gain":  "$0.00",
        "gainNumber":  0,
        "gainPct":  "+0.27%",
        "accountWeight":  "0.06%",
        "averageCostBasis":  "$61.56",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "EQIX",
        "description":  "EQUINIX INC COM",
        "quantity":  "0.002",
        "price":  "$1059.44",
        "priceChange":  "-$20.24",
        "marketValue":  "$2.11",
        "marketValueNumber":  2.11,
        "dayChange":  "-$0.05",
        "dayChangePct":  "-1.88%",
        "costBasis":  "$1.55",
        "gain":  "+$0.56",
        "gainNumber":  0.56,
        "gainPct":  "+36.70%",
        "accountWeight":  "0.07%",
        "averageCostBasis":  "$775.00",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "FCX",
        "description":  "FREEPORT-MCMORAN INC COM USD0.10",
        "quantity":  "0.049",
        "price":  "$63.01",
        "priceChange":  "-$3.13",
        "marketValue":  "$3.08",
        "marketValueNumber":  3.08,
        "dayChange":  "-$0.16",
        "dayChangePct":  "-4.74%",
        "costBasis":  "$1.99",
        "gain":  "+$1.09",
        "gainNumber":  1.09,
        "gainPct":  "+55.15%",
        "accountWeight":  "0.10%",
        "averageCostBasis":  "$40.61",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "FIGR",
        "description":  "FIGURE TECHNOLOGY SOLUTIO COM CL A",
        "quantity":  "0.5",
        "price":  "$43.28",
        "priceChange":  "+$0.06",
        "marketValue":  "$21.64",
        "marketValueNumber":  21.64,
        "dayChange":  "+$0.03",
        "dayChangePct":  "+0.13%",
        "costBasis":  "$17.11",
        "gain":  "+$4.53",
        "gainNumber":  4.53,
        "gainPct":  "+26.47%",
        "accountWeight":  "0.69%",
        "averageCostBasis":  "$34.22",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "ETN",
        "description":  "EATON CORPORATION PLC",
        "quantity":  "0.005",
        "price":  "$399.44",
        "priceChange":  "-$8.66",
        "marketValue":  "$1.99",
        "marketValueNumber":  1.99,
        "dayChange":  "-$0.05",
        "dayChangePct":  "-2.13%",
        "costBasis":  "$1.69",
        "gain":  "+$0.30",
        "gainNumber":  0.3,
        "gainPct":  "+18.17%",
        "accountWeight":  "0.06%",
        "averageCostBasis":  "$338.00",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "EQNR",
        "description":  "EQUINOR ASA SPON ADR EACH REP 1 ORD SHS",
        "quantity":  "0.083",
        "price":  "$39.48",
        "priceChange":  "+$1.36",
        "marketValue":  "$3.27",
        "marketValueNumber":  3.27,
        "dayChange":  "+$0.11",
        "dayChangePct":  "+3.56%",
        "costBasis":  "$1.98",
        "gain":  "+$1.29",
        "gainNumber":  1.29,
        "gainPct":  "+65.49%",
        "accountWeight":  "0.10%",
        "averageCostBasis":  "$23.86",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "ESTC",
        "description":  "ELASTIC N V COM EUR0.01",
        "quantity":  "0.022",
        "price":  "$50.60",
        "priceChange":  "+$0.82",
        "marketValue":  "$1.11",
        "marketValueNumber":  1.11,
        "dayChange":  "+$0.01",
        "dayChangePct":  "+1.64%",
        "costBasis":  "$1.93",
        "gain":  "-$0.82",
        "gainNumber":  -0.82,
        "gainPct":  "-42.33%",
        "accountWeight":  "0.04%",
        "averageCostBasis":  "$87.73",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "AMD",
        "description":  "ADVANCED MICRO DEVICES INC",
        "quantity":  "0.008",
        "price":  "$424.10",
        "priceChange":  "-$25.60",
        "marketValue":  "$3.39",
        "marketValueNumber":  3.39,
        "dayChange":  "-$0.21",
        "dayChangePct":  "-5.70%",
        "costBasis":  "$1.82",
        "gain":  "+$1.57",
        "gainNumber":  1.57,
        "gainPct":  "+86.41%",
        "accountWeight":  "0.11%",
        "averageCostBasis":  "$227.50",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "AMZN",
        "description":  "AMAZON.COM INC",
        "quantity":  "0.018",
        "price":  "$264.14",
        "priceChange":  "-$3.08",
        "marketValue":  "$4.75",
        "marketValueNumber":  4.75,
        "dayChange":  "-$0.06",
        "dayChangePct":  "-1.16%",
        "costBasis":  "$3.97",
        "gain":  "+$0.78",
        "gainNumber":  0.78,
        "gainPct":  "+19.76%",
        "accountWeight":  "0.15%",
        "averageCostBasis":  "$220.56",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "ABBV",
        "description":  "ABBVIE INC COM USD0.01",
        "quantity":  "0.008",
        "price":  "$210.39",
        "priceChange":  "-$0.38",
        "marketValue":  "$1.68",
        "marketValueNumber":  1.68,
        "dayChange":  "-$0.01",
        "dayChangePct":  "-0.19%",
        "costBasis":  "$1.87",
        "gain":  "-$0.19",
        "gainNumber":  -0.19,
        "gainPct":  "-10.00%",
        "accountWeight":  "0.05%",
        "averageCostBasis":  "$233.75",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "SPAXX**",
        "description":  "HELD IN MONEY MARKET",
        "quantity":  "",
        "price":  "",
        "priceChange":  "",
        "marketValue":  "$3.33",
        "marketValueNumber":  3.33,
        "dayChange":  "",
        "dayChangePct":  "",
        "costBasis":  "",
        "gain":  "",
        "gainNumber":  null,
        "gainPct":  "",
        "accountWeight":  "0.11%",
        "averageCostBasis":  "",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "AAPL",
        "description":  "APPLE INC",
        "quantity":  "1",
        "price":  "$300.23",
        "priceChange":  "+$2.02",
        "marketValue":  "$300.23",
        "marketValueNumber":  300.23,
        "dayChange":  "+$2.02",
        "dayChangePct":  "+0.67%",
        "costBasis":  "$280.48",
        "gain":  "+$19.75",
        "gainNumber":  19.75,
        "gainPct":  "+7.04%",
        "accountWeight":  "9.60%",
        "averageCostBasis":  "$280.48",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "ANET",
        "description":  "ARISTA NETWORKS INC COM SHS",
        "quantity":  "0.016",
        "price":  "$141.97",
        "priceChange":  "-$5.84",
        "marketValue":  "$2.27",
        "marketValueNumber":  2.27,
        "dayChange":  "-$0.10",
        "dayChangePct":  "-3.96%",
        "costBasis":  "$1.99",
        "gain":  "+$0.28",
        "gainNumber":  0.28,
        "gainPct":  "+14.14%",
        "accountWeight":  "0.07%",
        "averageCostBasis":  "$124.38",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "BWXT",
        "description":  "BWX TECHNOLOGIES INC COM",
        "quantity":  "0.011",
        "price":  "$204.72",
        "priceChange":  "-$6.22",
        "marketValue":  "$2.25",
        "marketValueNumber":  2.25,
        "dayChange":  "-$0.07",
        "dayChangePct":  "-2.95%",
        "costBasis":  "$1.91",
        "gain":  "+$0.34",
        "gainNumber":  0.34,
        "gainPct":  "+17.90%",
        "accountWeight":  "0.07%",
        "averageCostBasis":  "$173.64",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "CIEN",
        "description":  "CIENA CORP",
        "quantity":  "0.01",
        "price":  "$554.46",
        "priceChange":  "-$37.11",
        "marketValue":  "$5.54",
        "marketValueNumber":  5.54,
        "dayChange":  "-$0.38",
        "dayChangePct":  "-6.28%",
        "costBasis":  "$1.88",
        "gain":  "+$3.66",
        "gainNumber":  3.66,
        "gainPct":  "+194.92%",
        "accountWeight":  "0.18%",
        "averageCostBasis":  "$188.00",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "AWK",
        "description":  "AMERICAN WATER WORKS COMPANY INC COM USD0.01",
        "quantity":  "0.015",
        "price":  "$124.29",
        "priceChange":  "-$1.69",
        "marketValue":  "$1.86",
        "marketValueNumber":  1.86,
        "dayChange":  "-$0.03",
        "dayChangePct":  "-1.35%",
        "costBasis":  "$1.99",
        "gain":  "-$0.13",
        "gainNumber":  -0.13,
        "gainPct":  "-6.32%",
        "accountWeight":  "0.06%",
        "averageCostBasis":  "$132.67",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "ASML",
        "description":  "ASML HOLDING NV EUR0.09 NY REGISTRY SHS 2012",
        "quantity":  "0.001",
        "price":  "$1501.81",
        "priceChange":  "-$82.70",
        "marketValue":  "$1.50",
        "marketValueNumber":  1.5,
        "dayChange":  "-$0.09",
        "dayChangePct":  "-5.22%",
        "costBasis":  "$1.00",
        "gain":  "+$0.50",
        "gainNumber":  0.5,
        "gainPct":  "+50.18%",
        "accountWeight":  "0.05%",
        "averageCostBasis":  "$1000.00",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "AVGO",
        "description":  "BROADCOM INC COM",
        "quantity":  "0.005",
        "price":  "$425.19",
        "priceChange":  "-$14.60",
        "marketValue":  "$2.12",
        "marketValueNumber":  2.12,
        "dayChange":  "-$0.08",
        "dayChangePct":  "-3.32%",
        "costBasis":  "$1.69",
        "gain":  "+$0.43",
        "gainNumber":  0.43,
        "gainPct":  "+25.79%",
        "accountWeight":  "0.07%",
        "averageCostBasis":  "$338.00",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "FTNT",
        "description":  "FORTINET INC COM USD0.001",
        "quantity":  "0.024",
        "price":  "$122.78",
        "priceChange":  "+$0.92",
        "marketValue":  "$2.94",
        "marketValueNumber":  2.94,
        "dayChange":  "+$0.02",
        "dayChangePct":  "+0.75%",
        "costBasis":  "$1.94",
        "gain":  "+$1.00",
        "gainNumber":  1,
        "gainPct":  "+51.89%",
        "accountWeight":  "0.09%",
        "averageCostBasis":  "$80.83",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "NVDA",
        "description":  "NVIDIA CORPORATION COM",
        "quantity":  "0.032",
        "price":  "$225.32",
        "priceChange":  "-$10.42",
        "marketValue":  "$7.21",
        "marketValueNumber":  7.21,
        "dayChange":  "-$0.34",
        "dayChangePct":  "-4.43%",
        "costBasis":  "$5.82",
        "gain":  "+$1.39",
        "gainNumber":  1.39,
        "gainPct":  "+23.88%",
        "accountWeight":  "0.23%",
        "averageCostBasis":  "$181.88",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "PANW",
        "description":  "PALO ALTO NETWORKS INC COM USD0.0001",
        "quantity":  "0.009",
        "price":  "$242.83",
        "priceChange":  "+$4.62",
        "marketValue":  "$2.18",
        "marketValueNumber":  2.18,
        "dayChange":  "+$0.04",
        "dayChangePct":  "+1.93%",
        "costBasis":  "$1.81",
        "gain":  "+$0.37",
        "gainNumber":  0.37,
        "gainPct":  "+20.74%",
        "accountWeight":  "0.07%",
        "averageCostBasis":  "$201.11",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "NOW",
        "description":  "SERVICENOW INC COM USD0.001",
        "quantity":  "0.02",
        "price":  "$95.07",
        "priceChange":  "+$4.57",
        "marketValue":  "$1.90",
        "marketValueNumber":  1.9,
        "dayChange":  "+$0.09",
        "dayChangePct":  "+5.04%",
        "costBasis":  "$3.28",
        "gain":  "-$1.38",
        "gainNumber":  -1.38,
        "gainPct":  "-42.04%",
        "accountWeight":  "0.06%",
        "averageCostBasis":  "$164.00",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "MU",
        "description":  "MICRON TECHNOLOGY INC",
        "quantity":  "1",
        "price":  "$724.66",
        "priceChange":  "-$51.35",
        "marketValue":  "$724.66",
        "marketValueNumber":  724.66,
        "dayChange":  "-$51.35",
        "dayChangePct":  "-6.62%",
        "costBasis":  "$391.31",
        "gain":  "+$333.35",
        "gainNumber":  333.35,
        "gainPct":  "+85.18%",
        "accountWeight":  "23.17%",
        "averageCostBasis":  "$391.31",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "NEE",
        "description":  "NEXTERA ENERGY INC COM USD0.01",
        "quantity":  "0.023",
        "price":  "$93.36",
        "priceChange":  "-$2.32",
        "marketValue":  "$2.14",
        "marketValueNumber":  2.14,
        "dayChange":  "-$0.06",
        "dayChangePct":  "-2.43%",
        "costBasis":  "$1.98",
        "gain":  "+$0.16",
        "gainNumber":  0.16,
        "gainPct":  "+8.44%",
        "accountWeight":  "0.07%",
        "averageCostBasis":  "$86.09",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "PLTR",
        "description":  "PALANTIR TECHNOLOGIES INC CL A",
        "quantity":  "3",
        "price":  "$133.99",
        "priceChange":  "+$0.26",
        "marketValue":  "$401.97",
        "marketValueNumber":  401.97,
        "dayChange":  "+$0.78",
        "dayChangePct":  "+0.19%",
        "costBasis":  "$456.71",
        "gain":  "-$54.74",
        "gainNumber":  -54.74,
        "gainPct":  "-11.99%",
        "accountWeight":  "12.85%",
        "averageCostBasis":  "$152.24",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "SMR",
        "description":  "NUSCALE PWR CORP CL A COM",
        "quantity":  "0.091",
        "price":  "$11.23",
        "priceChange":  "-$0.83",
        "marketValue":  "$1.02",
        "marketValueNumber":  1.02,
        "dayChange":  "-$0.08",
        "dayChangePct":  "-6.89%",
        "costBasis":  "$1.98",
        "gain":  "-$0.96",
        "gainNumber":  -0.96,
        "gainPct":  "-48.39%",
        "accountWeight":  "0.03%",
        "averageCostBasis":  "$21.76",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "SNOW",
        "description":  "SNOWFLAKE INC. COMMON STOCK",
        "quantity":  "0.007",
        "price":  "$157.47",
        "priceChange":  "+$6.71",
        "marketValue":  "$1.10",
        "marketValueNumber":  1.1,
        "dayChange":  "+$0.04",
        "dayChangePct":  "+4.45%",
        "costBasis":  "$1.76",
        "gain":  "-$0.66",
        "gainNumber":  -0.66,
        "gainPct":  "-37.37%",
        "accountWeight":  "0.04%",
        "averageCostBasis":  "$251.43",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "SMCI",
        "description":  "SUPER MICRO COMPUTER INC COM NEW",
        "quantity":  "17.114",
        "price":  "$31.04",
        "priceChange":  "-$1.99",
        "marketValue":  "$531.21",
        "marketValueNumber":  531.21,
        "dayChange":  "-$34.06",
        "dayChangePct":  "-6.03%",
        "costBasis":  "$499.99",
        "gain":  "+$31.22",
        "gainNumber":  31.22,
        "gainPct":  "+6.24%",
        "accountWeight":  "16.98%",
        "averageCostBasis":  "$29.22",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "ROK",
        "description":  "ROCKWELL AUTOMATION INC COM USD1",
        "quantity":  "0.005",
        "price":  "$447.36",
        "priceChange":  "-$7.80",
        "marketValue":  "$2.23",
        "marketValueNumber":  2.23,
        "dayChange":  "-$0.04",
        "dayChangePct":  "-1.72%",
        "costBasis":  "$1.84",
        "gain":  "+$0.39",
        "gainNumber":  0.39,
        "gainPct":  "+21.56%",
        "accountWeight":  "0.07%",
        "averageCostBasis":  "$368.00",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "SCCO",
        "description":  "SOUTHERN COPPER CORP",
        "quantity":  "0.031",
        "price":  "$176.78",
        "priceChange":  "-$11.72",
        "marketValue":  "$5.48",
        "marketValueNumber":  5.48,
        "dayChange":  "-$0.37",
        "dayChangePct":  "-6.22%",
        "costBasis":  "$3.90",
        "gain":  "+$1.58",
        "gainNumber":  1.58,
        "gainPct":  "+40.51%",
        "accountWeight":  "0.18%",
        "averageCostBasis":  "$125.81",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "IBM",
        "description":  "INTERNATIONAL BUS MACH CORP COM USD0.20",
        "quantity":  "0.006",
        "price":  "$219.30",
        "priceChange":  "+$0.93",
        "marketValue":  "$1.31",
        "marketValueNumber":  1.31,
        "dayChange":  "$0.00",
        "dayChangePct":  "+0.42%",
        "costBasis":  "$1.75",
        "gain":  "-$0.44",
        "gainNumber":  -0.44,
        "gainPct":  "-24.82%",
        "accountWeight":  "0.04%",
        "averageCostBasis":  "$291.67",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "KMI",
        "description":  "KINDER MORGAN INC COM USD0.01",
        "quantity":  "0.073",
        "price":  "$33.63",
        "priceChange":  "+$0.23",
        "marketValue":  "$2.45",
        "marketValueNumber":  2.45,
        "dayChange":  "+$0.01",
        "dayChangePct":  "+0.68%",
        "costBasis":  "$1.97",
        "gain":  "+$0.48",
        "gainNumber":  0.48,
        "gainPct":  "+24.61%",
        "accountWeight":  "0.08%",
        "averageCostBasis":  "$26.99",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "GTLB",
        "description":  "GITLAB INC CLASS A COM",
        "quantity":  "0.047",
        "price":  "$23.66",
        "priceChange":  "+$1.06",
        "marketValue":  "$1.11",
        "marketValueNumber":  1.11,
        "dayChange":  "+$0.04",
        "dayChangePct":  "+4.69%",
        "costBasis":  "$2.00",
        "gain":  "-$0.89",
        "gainNumber":  -0.89,
        "gainPct":  "-44.40%",
        "accountWeight":  "0.04%",
        "averageCostBasis":  "$42.55",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "GOOG",
        "description":  "ALPHABET INC CAP STK CL C",
        "quantity":  "0.371",
        "price":  "$393.32",
        "priceChange":  "-$3.85",
        "marketValue":  "$145.92",
        "marketValueNumber":  145.92,
        "dayChange":  "-$1.43",
        "dayChangePct":  "-0.97%",
        "costBasis":  "$114.95",
        "gain":  "+$30.97",
        "gainNumber":  30.97,
        "gainPct":  "+26.94%",
        "accountWeight":  "4.67%",
        "averageCostBasis":  "$309.84",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "GOOGL",
        "description":  "ALPHABET INC CAP STK CL A",
        "quantity":  "0.622",
        "price":  "$396.78",
        "priceChange":  "-$4.29",
        "marketValue":  "$246.79",
        "marketValueNumber":  246.79,
        "dayChange":  "-$2.67",
        "dayChangePct":  "-1.07%",
        "costBasis":  "$206.07",
        "gain":  "+$40.72",
        "gainNumber":  40.72,
        "gainPct":  "+19.76%",
        "accountWeight":  "7.89%",
        "averageCostBasis":  "$331.30",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "LITE",
        "description":  "LUMENTUM HLDGS INC COM",
        "quantity":  "0.008",
        "price":  "$970.70",
        "priceChange":  "-$31.11",
        "marketValue":  "$7.76",
        "marketValueNumber":  7.76,
        "dayChange":  "-$0.25",
        "dayChangePct":  "-3.11%",
        "costBasis":  "$1.94",
        "gain":  "+$5.82",
        "gainNumber":  5.82,
        "gainPct":  "+300.28%",
        "accountWeight":  "0.25%",
        "averageCostBasis":  "$242.50",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "MRVL",
        "description":  "MARVELL TECHNOLOGY INC COM",
        "quantity":  "0.024",
        "price":  "$176.89",
        "priceChange":  "-$5.69",
        "marketValue":  "$4.24",
        "marketValueNumber":  4.24,
        "dayChange":  "-$0.14",
        "dayChangePct":  "-3.12%",
        "costBasis":  "$1.93",
        "gain":  "+$2.31",
        "gainNumber":  2.31,
        "gainPct":  "+119.96%",
        "accountWeight":  "0.14%",
        "averageCostBasis":  "$80.42",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "MSFT",
        "description":  "MICROSOFT CORP",
        "quantity":  "0.012",
        "price":  "$421.92",
        "priceChange":  "+$12.49",
        "marketValue":  "$5.06",
        "marketValueNumber":  5.06,
        "dayChange":  "+$0.14",
        "dayChangePct":  "+3.05%",
        "costBasis":  "$5.92",
        "gain":  "-$0.86",
        "gainNumber":  -0.86,
        "gainPct":  "-14.48%",
        "accountWeight":  "0.16%",
        "averageCostBasis":  "$493.33",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "MLM",
        "description":  "MARTIN MARIETTA MATERIALS INC COM USD0.01",
        "quantity":  "0.003",
        "price":  "$558.66",
        "priceChange":  "-$16.57",
        "marketValue":  "$1.67",
        "marketValueNumber":  1.67,
        "dayChange":  "-$0.05",
        "dayChangePct":  "-2.89%",
        "costBasis":  "$1.78",
        "gain":  "-$0.11",
        "gainNumber":  -0.11,
        "gainPct":  "-5.85%",
        "accountWeight":  "0.05%",
        "averageCostBasis":  "$593.33",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "LNG",
        "description":  "CHENIERE ENERGY INC COM USD0.003",
        "quantity":  "0.009",
        "price":  "$241.84",
        "priceChange":  "+$0.76",
        "marketValue":  "$2.17",
        "marketValueNumber":  2.17,
        "dayChange":  "$0.00",
        "dayChangePct":  "+0.31%",
        "costBasis":  "$1.93",
        "gain":  "+$0.24",
        "gainNumber":  0.24,
        "gainPct":  "+12.77%",
        "accountWeight":  "0.07%",
        "averageCostBasis":  "$214.44",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    },
    {
        "brokerage":  "Fidelity",
        "accountName":  "Individual",
        "symbol":  "MDB",
        "description":  "MONGODB INC CL A",
        "quantity":  "0.005",
        "price":  "$312.16",
        "priceChange":  "+$9.07",
        "marketValue":  "$1.56",
        "marketValueNumber":  1.56,
        "dayChange":  "+$0.04",
        "dayChangePct":  "+2.99%",
        "costBasis":  "$1.68",
        "gain":  "-$0.12",
        "gainNumber":  -0.12,
        "gainPct":  "-7.10%",
        "accountWeight":  "0.05%",
        "averageCostBasis":  "$336.00",
        "assetType":  "Cash",
        "reinvest":  "",
        "reinvestCapitalGains":  ""
    }
];

