window.allHoldingsDetail = [
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "AI",
        "description": "C3 AI INC CLASS A",
        "quantity": "3",
        "price": "9.43",
        "priceChange": "+$0.37",
        "marketValue": "$28.29",
        "marketValueNumber": 28.29,
        "dayChange": "+$1.11",
        "dayChangePct": "+4.08%",
        "costBasis": "$81.35",
        "gain": "-$53.06",
        "gainNumber": -53.06,
        "gainPct": "-65.22%",
        "accountWeight": "",
        "averageCostBasis": "$27.12",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "AIO",
        "description": "VIRTUS ARTIFICIAL INTELL",
        "quantity": "5",
        "price": "26.99",
        "priceChange": "-$0.05",
        "marketValue": "$134.95",
        "marketValueNumber": 134.95,
        "dayChange": "-$0.25",
        "dayChangePct": "-0.18%",
        "costBasis": "$122.56",
        "gain": "+$12.39",
        "gainNumber": 12.39,
        "gainPct": "+10.11%",
        "accountWeight": "",
        "averageCostBasis": "$24.51",
        "assetType": "ETFs & Closed End Funds",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "AMD",
        "description": "ADVANCED MICRO DEVIC",
        "quantity": "1",
        "price": "557.68",
        "priceChange": "+$39.86",
        "marketValue": "$557.68",
        "marketValueNumber": 557.68,
        "dayChange": "+$39.86",
        "dayChangePct": "+7.70%",
        "costBasis": "$121.53",
        "gain": "+$436.15",
        "gainNumber": 436.15,
        "gainPct": "+358.88%",
        "accountWeight": "",
        "averageCostBasis": "$121.53",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "AMZN",
        "description": "AMAZON.COM INC",
        "quantity": "1",
        "price": "244.92",
        "priceChange": "+$2.25",
        "marketValue": "$244.92",
        "marketValueNumber": 244.92,
        "dayChange": "+$2.25",
        "dayChangePct": "+0.93%",
        "costBasis": "$176.74",
        "gain": "+$68.18",
        "gainNumber": 68.18,
        "gainPct": "+38.58%",
        "accountWeight": "",
        "averageCostBasis": "$176.74",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "ARTY",
        "description": "ISHARES FUTURE AI & TECHETF",
        "quantity": "2",
        "price": "72.72",
        "priceChange": "+$1.63",
        "marketValue": "$145.44",
        "marketValueNumber": 145.44,
        "dayChange": "+$3.26",
        "dayChangePct": "+2.29%",
        "costBasis": "$66.19",
        "gain": "+$79.25",
        "gainNumber": 79.25,
        "gainPct": "+119.73%",
        "accountWeight": "",
        "averageCostBasis": "$33.10",
        "assetType": "ETFs & Closed End Funds",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "BITC",
        "description": "BITWISE TRENDWISE BITCOIN AND TREASURIES ROTATION STRATEGY ETF",
        "quantity": "1",
        "price": "36.25",
        "priceChange": "-$0.04",
        "marketValue": "$36.25",
        "marketValueNumber": 36.25,
        "dayChange": "-$0.04",
        "dayChangePct": "-0.11%",
        "costBasis": "$72.87",
        "gain": "-$36.62",
        "gainNumber": -36.62,
        "gainPct": "-50.25%",
        "accountWeight": "",
        "averageCostBasis": "$72.87",
        "assetType": "ETFs & Closed End Funds",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "BTX",
        "description": "BLACKROCK TECH AND PRIVA",
        "quantity": "20",
        "price": "8.73",
        "priceChange": "+$0.13",
        "marketValue": "$174.60",
        "marketValueNumber": 174.6,
        "dayChange": "+$2.60",
        "dayChangePct": "+1.51%",
        "costBasis": "$148.30",
        "gain": "+$26.30",
        "gainNumber": 26.3,
        "gainPct": "+17.73%",
        "accountWeight": "",
        "averageCostBasis": "$7.42",
        "assetType": "ETFs & Closed End Funds",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "CHAT",
        "description": "ROUNDHILL GENERATIVE AI & TECHNOLOGY ETF",
        "quantity": "20",
        "price": "91.30",
        "priceChange": "+$2.51",
        "marketValue": "$1,826.00",
        "marketValueNumber": 1826.0,
        "dayChange": "+$50.20",
        "dayChangePct": "+2.83%",
        "costBasis": "$1,129.53",
        "gain": "+$696.47",
        "gainNumber": 696.47,
        "gainPct": "+61.66%",
        "accountWeight": "",
        "averageCostBasis": "$56.48",
        "assetType": "ETFs & Closed End Funds",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "D",
        "description": "DOMINION ENERGY INC",
        "quantity": "1",
        "price": "69.21",
        "priceChange": "-$0.54",
        "marketValue": "$69.21",
        "marketValueNumber": 69.21,
        "dayChange": "-$0.54",
        "dayChangePct": "-0.77%",
        "costBasis": "$55.72",
        "gain": "+$13.49",
        "gainNumber": 13.49,
        "gainPct": "+24.21%",
        "accountWeight": "",
        "averageCostBasis": "$55.72",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "DRAM",
        "description": "ROUNDHILL MEMORY ETF",
        "quantity": "4",
        "price": "64.96",
        "priceChange": "+$4.33",
        "marketValue": "$259.84",
        "marketValueNumber": 259.84,
        "dayChange": "+$17.32",
        "dayChangePct": "+7.14%",
        "costBasis": "$222.87",
        "gain": "+$36.97",
        "gainNumber": 36.97,
        "gainPct": "+16.59%",
        "accountWeight": "",
        "averageCostBasis": "$55.71",
        "assetType": "ETFs & Closed End Funds",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "DUK",
        "description": "DUKE ENERGY CORP NEW",
        "quantity": "1",
        "price": "126.68",
        "priceChange": "-$2.92",
        "marketValue": "$126.68",
        "marketValueNumber": 126.68,
        "dayChange": "-$2.92",
        "dayChangePct": "-2.25%",
        "costBasis": "$111.55",
        "gain": "+$15.13",
        "gainNumber": 15.13,
        "gainPct": "+13.56%",
        "accountWeight": "",
        "averageCostBasis": "$111.55",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "EXEL",
        "description": "EXELIXIS INC",
        "quantity": "2",
        "price": "55.59",
        "priceChange": "-$0.27",
        "marketValue": "$111.17",
        "marketValueNumber": 111.17,
        "dayChange": "-$0.53",
        "dayChangePct": "-0.47%",
        "costBasis": "$43.73",
        "gain": "+$67.44",
        "gainNumber": 67.44,
        "gainPct": "+154.22%",
        "accountWeight": "",
        "averageCostBasis": "$21.86",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "FLNC",
        "description": "FLNC",
        "quantity": "9",
        "price": "18.03",
        "priceChange": "+$1.03",
        "marketValue": "$162.27",
        "marketValueNumber": 162.27,
        "dayChange": "+$9.27",
        "dayChangePct": "+6.06%",
        "costBasis": "$195.78",
        "gain": "-$33.51",
        "gainNumber": -33.51,
        "gainPct": "-17.12%",
        "accountWeight": "",
        "averageCostBasis": "$21.75",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "GOOGL",
        "description": "ALPHABET INC CLASS A",
        "quantity": "1",
        "price": "364.23",
        "priceChange": "+$4.32",
        "marketValue": "$364.23",
        "marketValueNumber": 364.23,
        "dayChange": "+$4.32",
        "dayChangePct": "+1.20%",
        "costBasis": "$163.33",
        "gain": "+$200.90",
        "gainNumber": 200.9,
        "gainPct": "+123.00%",
        "accountWeight": "",
        "averageCostBasis": "$163.33",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "HLX",
        "description": "HELIX ENERGY SOLUTIONS G",
        "quantity": "4",
        "price": "8.61",
        "priceChange": "+$0.07",
        "marketValue": "$34.42",
        "marketValueNumber": 34.42,
        "dayChange": "+$0.26",
        "dayChangePct": "+0.76%",
        "costBasis": "$41.52",
        "gain": "-$7.10",
        "gainNumber": -7.1,
        "gainPct": "-17.10%",
        "accountWeight": "",
        "averageCostBasis": "$10.38",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "IBIT",
        "description": "ISHARES BITCOIN TRUST ETF",
        "quantity": "1",
        "price": "36.06",
        "priceChange": "+$1.20",
        "marketValue": "$36.06",
        "marketValueNumber": 36.06,
        "dayChange": "+$1.20",
        "dayChangePct": "+3.43%",
        "costBasis": "$40.53",
        "gain": "-$4.47",
        "gainNumber": -4.47,
        "gainPct": "-11.03%",
        "accountWeight": "",
        "averageCostBasis": "$40.53",
        "assetType": "ETFs & Closed End Funds",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "INTC",
        "description": "INTEL CORP",
        "quantity": "3",
        "price": "124.06",
        "priceChange": "+$3.71",
        "marketValue": "$372.17",
        "marketValueNumber": 372.17,
        "dayChange": "+$11.12",
        "dayChangePct": "+3.08%",
        "costBasis": "$101.43",
        "gain": "+$270.74",
        "gainNumber": 270.74,
        "gainPct": "+266.92%",
        "accountWeight": "",
        "averageCostBasis": "$33.81",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "LRNZ",
        "description": "TRUESHARES TECHNOLOGY, AI AND DEEP LEARNING ETF",
        "quantity": "2",
        "price": "63.52",
        "priceChange": "+$1.60",
        "marketValue": "$127.04",
        "marketValueNumber": 127.04,
        "dayChange": "+$3.19",
        "dayChangePct": "+2.58%",
        "costBasis": "$68.68",
        "gain": "+$58.36",
        "gainNumber": 58.36,
        "gainPct": "+84.97%",
        "accountWeight": "",
        "averageCostBasis": "$0.00",
        "assetType": "ETFs & Closed End Funds",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "LTRX",
        "description": "LANTRONIX INC",
        "quantity": "6",
        "price": "5.66",
        "priceChange": "+$0.17",
        "marketValue": "$33.93",
        "marketValueNumber": 33.93,
        "dayChange": "+$0.99",
        "dayChangePct": "+3.01%",
        "costBasis": "$29.35",
        "gain": "+$4.58",
        "gainNumber": 4.58,
        "gainPct": "+15.60%",
        "accountWeight": "",
        "averageCostBasis": "$4.89",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "MSFT",
        "description": "MICROSOFT CORP",
        "quantity": "1",
        "price": "386.08",
        "priceChange": "-$4.41",
        "marketValue": "$386.08",
        "marketValueNumber": 386.08,
        "dayChange": "-$4.41",
        "dayChangePct": "-1.13%",
        "costBasis": "$408.02",
        "gain": "-$21.94",
        "gainNumber": -21.94,
        "gainPct": "-5.38%",
        "accountWeight": "",
        "averageCostBasis": "$408.02",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "MXL",
        "description": "MAXLINEAR INC CLASS CLASS A",
        "quantity": "4",
        "price": "99.90",
        "priceChange": "+$6.78",
        "marketValue": "$399.60",
        "marketValueNumber": 399.6,
        "dayChange": "+$27.12",
        "dayChangePct": "+7.28%",
        "costBasis": "$174.51",
        "gain": "+$225.09",
        "gainNumber": 225.09,
        "gainPct": "+128.98%",
        "accountWeight": "",
        "averageCostBasis": "$43.63",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "NVDA",
        "description": "NVIDIA CORP",
        "quantity": "2",
        "price": "196.50",
        "priceChange": "+$1.67",
        "marketValue": "$392.99",
        "marketValueNumber": 392.99,
        "dayChange": "+$3.33",
        "dayChangePct": "+0.85%",
        "costBasis": "$248.52",
        "gain": "+$144.47",
        "gainNumber": 144.47,
        "gainPct": "+58.13%",
        "accountWeight": "",
        "averageCostBasis": "$124.26",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "PATH",
        "description": "UIPATH INC CLASS CLASS A",
        "quantity": "2",
        "price": "12.23",
        "priceChange": "+$0.52",
        "marketValue": "$24.46",
        "marketValueNumber": 24.46,
        "dayChange": "+$1.04",
        "dayChangePct": "+4.44%",
        "costBasis": "$41.67",
        "gain": "-$17.21",
        "gainNumber": -17.21,
        "gainPct": "-41.30%",
        "accountWeight": "",
        "averageCostBasis": "$20.83",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "ROBT",
        "description": "FIRST TRUST NASDAQ ARTIFICIAL INTELLIGENCE AND ROBOTICS ETF",
        "quantity": "5",
        "price": "57.43",
        "priceChange": "+$1.18",
        "marketValue": "$287.15",
        "marketValueNumber": 287.15,
        "dayChange": "+$5.88",
        "dayChangePct": "+2.09%",
        "costBasis": "$250.83",
        "gain": "+$36.32",
        "gainNumber": 36.32,
        "gainPct": "+14.48%",
        "accountWeight": "",
        "averageCostBasis": "$50.16",
        "assetType": "ETFs & Closed End Funds",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "SLV",
        "description": "ISHARES SILVER TRUST",
        "quantity": "2",
        "price": "55.89",
        "priceChange": "+$0.87",
        "marketValue": "$111.78",
        "marketValueNumber": 111.78,
        "dayChange": "+$1.74",
        "dayChangePct": "+1.58%",
        "costBasis": "$90.45",
        "gain": "+$21.33",
        "gainNumber": 21.33,
        "gainPct": "+23.58%",
        "accountWeight": "",
        "averageCostBasis": "$45.23",
        "assetType": "ETFs & Closed End Funds",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "SOUN",
        "description": "SOUNDHOUND AI INC CLASS A",
        "quantity": "10",
        "price": "6.93",
        "priceChange": "+$0.39",
        "marketValue": "$69.35",
        "marketValueNumber": 69.35,
        "dayChange": "+$3.85",
        "dayChangePct": "+5.88%",
        "costBasis": "$21.35",
        "gain": "+$48.00",
        "gainNumber": 48.0,
        "gainPct": "+224.82%",
        "accountWeight": "",
        "averageCostBasis": "$2.13",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "SPRX",
        "description": "SPEAR ALPHA ETF",
        "quantity": "2",
        "price": "52.20",
        "priceChange": "+$1.46",
        "marketValue": "$104.40",
        "marketValueNumber": 104.4,
        "dayChange": "+$2.92",
        "dayChangePct": "+2.88%",
        "costBasis": "$47.86",
        "gain": "+$56.54",
        "gainNumber": 56.54,
        "gainPct": "+118.14%",
        "accountWeight": "",
        "averageCostBasis": "$23.93",
        "assetType": "ETFs & Closed End Funds",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "SYM",
        "description": "SYMBOTIC INC CLASS A",
        "quantity": "2",
        "price": "43.95",
        "priceChange": "+$1.21",
        "marketValue": "$87.90",
        "marketValueNumber": 87.9,
        "dayChange": "+$2.42",
        "dayChangePct": "+2.83%",
        "costBasis": "$79.98",
        "gain": "+$7.92",
        "gainNumber": 7.92,
        "gainPct": "+9.90%",
        "accountWeight": "",
        "averageCostBasis": "$39.99",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "TEM",
        "description": "TEMPUS AI INC CLASS CLASS A",
        "quantity": "2",
        "price": "61.02",
        "priceChange": "+$0.74",
        "marketValue": "$122.03",
        "marketValueNumber": 122.03,
        "dayChange": "+$1.49",
        "dayChangePct": "+1.24%",
        "costBasis": "$142.54",
        "gain": "-$20.51",
        "gainNumber": -20.51,
        "gainPct": "-14.39%",
        "accountWeight": "",
        "averageCostBasis": "$71.27",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "U",
        "description": "UNITY SOFTWARE INC",
        "quantity": "2",
        "price": "29.84",
        "priceChange": "+$0.53",
        "marketValue": "$59.69",
        "marketValueNumber": 59.69,
        "dayChange": "+$1.05",
        "dayChangePct": "+1.79%",
        "costBasis": "$50.92",
        "gain": "+$8.77",
        "gainNumber": 8.77,
        "gainPct": "+17.22%",
        "accountWeight": "",
        "averageCostBasis": "$25.46",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "UPST",
        "description": "UPSTART HLDGS INC",
        "quantity": "1",
        "price": "34.13",
        "priceChange": "-$0.65",
        "marketValue": "$34.13",
        "marketValueNumber": 34.13,
        "dayChange": "-$0.65",
        "dayChangePct": "-1.87%",
        "costBasis": "$24.52",
        "gain": "+$9.61",
        "gainNumber": 9.61,
        "gainPct": "+39.19%",
        "accountWeight": "",
        "averageCostBasis": "$24.52",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "WTAI",
        "description": "WISDOMTREE ARTIFICIAL INTELLIGENCE AND INNOVATION FUND",
        "quantity": "3",
        "price": "44.11",
        "priceChange": "+$1.54",
        "marketValue": "$132.33",
        "marketValueNumber": 132.33,
        "dayChange": "+$4.62",
        "dayChangePct": "+3.62%",
        "costBasis": "$68.38",
        "gain": "+$63.95",
        "gainNumber": 63.95,
        "gainPct": "+93.52%",
        "accountWeight": "",
        "averageCostBasis": "$22.79",
        "assetType": "ETFs & Closed End Funds",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "WULF",
        "description": "WULF",
        "quantity": "1",
        "price": "23.23",
        "priceChange": "+$2.06",
        "marketValue": "$23.24",
        "marketValueNumber": 23.24,
        "dayChange": "+$2.05",
        "dayChangePct": "+9.70%",
        "costBasis": "$25.16",
        "gain": "-$1.93",
        "gainNumber": -1.93,
        "gainPct": "-7.67%",
        "accountWeight": "",
        "averageCostBasis": "$25.16",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "XLE",
        "description": "STATE STREET ENERGY SELECT SECTOR SPDR ETF",
        "quantity": "4",
        "price": "53.23",
        "priceChange": "+$0.01",
        "marketValue": "$212.90",
        "marketValueNumber": 212.9,
        "dayChange": "+$0.02",
        "dayChangePct": "+0.01%",
        "costBasis": "$181.82",
        "gain": "+$31.08",
        "gainNumber": 31.08,
        "gainPct": "+17.09%",
        "accountWeight": "",
        "averageCostBasis": "$45.46",
        "assetType": "ETFs & Closed End Funds",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "XLF",
        "description": "STATE STREET FINANCIAL SELECT SECTOR SPDR ETF",
        "quantity": "1",
        "price": "55.95",
        "priceChange": "+$0.34",
        "marketValue": "$55.96",
        "marketValueNumber": 55.96,
        "dayChange": "+$0.34",
        "dayChangePct": "+0.60%",
        "costBasis": "$49.17",
        "gain": "+$6.78",
        "gainNumber": 6.78,
        "gainPct": "+13.79%",
        "accountWeight": "",
        "averageCostBasis": "$49.17",
        "assetType": "ETFs & Closed End Funds",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "XT",
        "description": "ISHARES FUTURE EXPONENTIAL TECHNOLOGIESETF",
        "quantity": "2",
        "price": "83.35",
        "priceChange": "+$1.11",
        "marketValue": "$166.70",
        "marketValueNumber": 166.7,
        "dayChange": "+$2.22",
        "dayChangePct": "+1.35%",
        "costBasis": "$109.18",
        "gain": "+$57.52",
        "gainNumber": 57.52,
        "gainPct": "+52.68%",
        "accountWeight": "",
        "averageCostBasis": "$54.59",
        "assetType": "ETFs & Closed End Funds",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "thinkorswim",
        "accountName": "Individual",
        "symbol": "CASH",
        "description": "CASH",
        "quantity": "0",
        "price": "0.00",
        "priceChange": "+$0.00",
        "marketValue": "$51.48",
        "marketValueNumber": 51.48,
        "dayChange": "+$0.00",
        "dayChangePct": "+0.00%",
        "costBasis": "$51.48",
        "gain": "+$0.00",
        "gainNumber": 0.0,
        "gainPct": "+0.00%",
        "accountWeight": "",
        "averageCostBasis": "$0.00",
        "assetType": "Equity",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "SPAXX**",
        "description": "HELD IN MONEY MARKET",
        "quantity": "",
        "price": "",
        "priceChange": "",
        "marketValue": "$206.64",
        "marketValueNumber": 206.64,
        "dayChange": "",
        "dayChangePct": "",
        "costBasis": "",
        "gain": "",
        "gainNumber": null,
        "gainPct": "",
        "accountWeight": "4.96%",
        "averageCostBasis": "",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "AAPL",
        "description": "APPLE INC",
        "quantity": "1",
        "price": "$313.37",
        "priceChange": "+$4.74",
        "marketValue": "$313.37",
        "marketValueNumber": 313.37,
        "dayChange": "+$4.74",
        "dayChangePct": "+1.53%",
        "costBasis": "$280.48",
        "gain": "+$32.89",
        "gainNumber": 32.89,
        "gainPct": "+11.72%",
        "accountWeight": "7.52%",
        "averageCostBasis": "$280.48",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "ABBV",
        "description": "ABBVIE INC COM USD0.01",
        "quantity": "0.008",
        "price": "$255.80",
        "priceChange": "-$5.27",
        "marketValue": "$2.04",
        "marketValueNumber": 2.04,
        "dayChange": "-$0.05",
        "dayChangePct": "-2.02%",
        "costBasis": "$1.87",
        "gain": "+$0.17",
        "gainNumber": 0.17,
        "gainPct": "+9.43%",
        "accountWeight": "0.05%",
        "averageCostBasis": "$233.75",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "AMD",
        "description": "ADVANCED MICRO DEVICES INC",
        "quantity": "0.008",
        "price": "$552.38",
        "priceChange": "+$34.56",
        "marketValue": "$4.41",
        "marketValueNumber": 4.41,
        "dayChange": "+$0.27",
        "dayChangePct": "+6.67%",
        "costBasis": "$1.82",
        "gain": "+$2.59",
        "gainNumber": 2.59,
        "gainPct": "+142.80%",
        "accountWeight": "0.11%",
        "averageCostBasis": "$227.50",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "AMZN",
        "description": "AMAZON.COM INC",
        "quantity": "0.018",
        "price": "$245.41",
        "priceChange": "+$2.74",
        "marketValue": "$4.41",
        "marketValueNumber": 4.41,
        "dayChange": "+$0.04",
        "dayChangePct": "+1.12%",
        "costBasis": "$3.97",
        "gain": "+$0.44",
        "gainNumber": 0.44,
        "gainPct": "+11.26%",
        "accountWeight": "0.11%",
        "averageCostBasis": "$220.56",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "ANET",
        "description": "ARISTA NETWORKS INC COM SHS",
        "quantity": "0.016",
        "price": "$171.8848",
        "priceChange": "+$11.89",
        "marketValue": "$2.75",
        "marketValueNumber": 2.75,
        "dayChange": "+$0.19",
        "dayChangePct": "+7.43%",
        "costBasis": "$1.99",
        "gain": "+$0.76",
        "gainNumber": 0.76,
        "gainPct": "+38.19%",
        "accountWeight": "0.07%",
        "averageCostBasis": "$124.38",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "ASML",
        "description": "ASML HOLDING NV EUR0.09 NY REGISTRY SHS 2012",
        "quantity": "0.126",
        "price": "$1839.745",
        "priceChange": "+$70.42",
        "marketValue": "$231.80",
        "marketValueNumber": 231.8,
        "dayChange": "+$8.87",
        "dayChangePct": "+3.98%",
        "costBasis": "$199.87",
        "gain": "+$31.93",
        "gainNumber": 31.93,
        "gainPct": "+15.97%",
        "accountWeight": "5.56%",
        "averageCostBasis": "$1586.27",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "AVGO",
        "description": "BROADCOM INC COM",
        "quantity": "0.005",
        "price": "$375.27",
        "priceChange": "+$14.82",
        "marketValue": "$1.87",
        "marketValueNumber": 1.87,
        "dayChange": "+$0.07",
        "dayChangePct": "+4.11%",
        "costBasis": "$1.69",
        "gain": "+$0.18",
        "gainNumber": 0.18,
        "gainPct": "+11.02%",
        "accountWeight": "0.04%",
        "averageCostBasis": "$338.00",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "AWK",
        "description": "AMERICAN WATER WORKS COMPANY INC COM USD0.01",
        "quantity": "0.015",
        "price": "$133.28",
        "priceChange": "-$3.58",
        "marketValue": "$1.99",
        "marketValueNumber": 1.99,
        "dayChange": "-$0.06",
        "dayChangePct": "-2.62%",
        "costBasis": "$1.99",
        "gain": "+$0.00",
        "gainNumber": 0.0,
        "gainPct": "+0.46%",
        "accountWeight": "0.05%",
        "averageCostBasis": "$132.67",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "BWXT",
        "description": "BWX TECHNOLOGIES INC COM",
        "quantity": "0.011",
        "price": "$196.845",
        "priceChange": "+$5.79",
        "marketValue": "$2.16",
        "marketValueNumber": 2.16,
        "dayChange": "+$0.06",
        "dayChangePct": "+3.02%",
        "costBasis": "$1.91",
        "gain": "+$0.25",
        "gainNumber": 0.25,
        "gainPct": "+13.36%",
        "accountWeight": "0.05%",
        "averageCostBasis": "$173.64",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "CIEN",
        "description": "CIENA CORP",
        "quantity": "0.01",
        "price": "$433.01",
        "priceChange": "+$10.55",
        "marketValue": "$4.33",
        "marketValueNumber": 4.33,
        "dayChange": "+$0.10",
        "dayChangePct": "+2.49%",
        "costBasis": "$1.88",
        "gain": "+$2.45",
        "gainNumber": 2.45,
        "gainPct": "+130.32%",
        "accountWeight": "0.10%",
        "averageCostBasis": "$188.00",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "CRWD",
        "description": "CROWDSTRIKE HLDGS INC CL A",
        "quantity": "1.176",
        "price": "$198.605",
        "priceChange": "+$4.62",
        "marketValue": "$233.55",
        "marketValueNumber": 233.55,
        "dayChange": "+$5.43",
        "dayChangePct": "+2.38%",
        "costBasis": "$201.35",
        "gain": "+$32.20",
        "gainNumber": 32.2,
        "gainPct": "+15.99%",
        "accountWeight": "5.60%",
        "averageCostBasis": "$171.22",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "D",
        "description": "DOMINION ENERGY INC COM",
        "quantity": "0.032",
        "price": "$69.295",
        "priceChange": "-$0.46",
        "marketValue": "$2.21",
        "marketValueNumber": 2.21,
        "dayChange": "-$0.02",
        "dayChangePct": "-0.66%",
        "costBasis": "$1.97",
        "gain": "+$0.24",
        "gainNumber": 0.24,
        "gainPct": "+12.56%",
        "accountWeight": "0.05%",
        "averageCostBasis": "$61.56",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "DLR",
        "description": "DIGITAL REALTY TRUST INC",
        "quantity": "0.012",
        "price": "$172.76",
        "priceChange": "-$0.54",
        "marketValue": "$2.07",
        "marketValueNumber": 2.07,
        "dayChange": "-$0.01",
        "dayChangePct": "-0.32%",
        "costBasis": "$1.89",
        "gain": "+$0.18",
        "gainNumber": 0.18,
        "gainPct": "+9.68%",
        "accountWeight": "0.05%",
        "averageCostBasis": "$157.50",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "DRAM",
        "description": "ROUNDHILL ETF TRUST MEMORY ETF",
        "quantity": "5.176",
        "price": "$64.65",
        "priceChange": "+$4.02",
        "marketValue": "$334.62",
        "marketValueNumber": 334.62,
        "dayChange": "+$20.80",
        "dayChangePct": "+6.63%",
        "costBasis": "$280.00",
        "gain": "+$54.62",
        "gainNumber": 54.62,
        "gainPct": "+19.51%",
        "accountWeight": "8.03%",
        "averageCostBasis": "$54.10",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "DUK",
        "description": "DUKE ENERGY CORP NEW COM NEW ISIN #US26441C2044 SEDOL #B7JZSK0",
        "quantity": "0.016",
        "price": "$126.53",
        "priceChange": "-$3.07",
        "marketValue": "$2.02",
        "marketValueNumber": 2.02,
        "dayChange": "-$0.05",
        "dayChangePct": "-2.37%",
        "costBasis": "$1.98",
        "gain": "+$0.04",
        "gainNumber": 0.04,
        "gainPct": "+2.24%",
        "accountWeight": "0.05%",
        "averageCostBasis": "$123.75",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "EQIX",
        "description": "EQUINIX INC COM",
        "quantity": "0.002",
        "price": "$995.085",
        "priceChange": "-$6.93",
        "marketValue": "$1.99",
        "marketValueNumber": 1.99,
        "dayChange": "-$0.02",
        "dayChangePct": "-0.70%",
        "costBasis": "$1.55",
        "gain": "+$0.44",
        "gainNumber": 0.44,
        "gainPct": "+28.39%",
        "accountWeight": "0.05%",
        "averageCostBasis": "$775.00",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "EQNR",
        "description": "EQUINOR ASA SPON ADR EACH REP 1 ORD SHS",
        "quantity": "0.083",
        "price": "$31.995",
        "priceChange": "-$0.04",
        "marketValue": "$2.65",
        "marketValueNumber": 2.65,
        "dayChange": "-$0.01",
        "dayChangePct": "-0.15%",
        "costBasis": "$1.98",
        "gain": "+$0.67",
        "gainNumber": 0.67,
        "gainPct": "+34.12%",
        "accountWeight": "0.06%",
        "averageCostBasis": "$23.86",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "ESTC",
        "description": "ELASTIC N V COM EUR0.01",
        "quantity": "0.022",
        "price": "$58.15",
        "priceChange": "+$0.11",
        "marketValue": "$1.27",
        "marketValueNumber": 1.27,
        "dayChange": "+$0.00",
        "dayChangePct": "+0.18%",
        "costBasis": "$1.93",
        "gain": "-$0.66",
        "gainNumber": -0.66,
        "gainPct": "-33.72%",
        "accountWeight": "0.03%",
        "averageCostBasis": "$87.73",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "ETN",
        "description": "EATON CORPORATION PLC",
        "quantity": "0.005",
        "price": "$413.27",
        "priceChange": "+$14.75",
        "marketValue": "$2.06",
        "marketValueNumber": 2.06,
        "dayChange": "+$0.07",
        "dayChangePct": "+3.70%",
        "costBasis": "$1.69",
        "gain": "+$0.37",
        "gainNumber": 0.37,
        "gainPct": "+22.26%",
        "accountWeight": "0.05%",
        "averageCostBasis": "$338.00",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "FCX",
        "description": "FREEPORT-MCMORAN INC COM USD0.10",
        "quantity": "0.049",
        "price": "$60.67",
        "priceChange": "-$0.30",
        "marketValue": "$2.97",
        "marketValueNumber": 2.97,
        "dayChange": "-$0.02",
        "dayChangePct": "-0.50%",
        "costBasis": "$1.99",
        "gain": "+$0.98",
        "gainNumber": 0.98,
        "gainPct": "+49.38%",
        "accountWeight": "0.07%",
        "averageCostBasis": "$40.61",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "FIGR",
        "description": "FIGURE TECHNOLOGY SOLUTIO COM CL A",
        "quantity": "0.5",
        "price": "$33.91",
        "priceChange": "+$0.00",
        "marketValue": "$16.95",
        "marketValueNumber": 16.95,
        "dayChange": "+$0.00",
        "dayChangePct": "+0.00%",
        "costBasis": "$17.11",
        "gain": "-$0.16",
        "gainNumber": -0.16,
        "gainPct": "-0.91%",
        "accountWeight": "0.41%",
        "averageCostBasis": "$34.22",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "FTNT",
        "description": "FORTINET INC COM USD0.001",
        "quantity": "0.024",
        "price": "$162.225",
        "priceChange": "+$5.97",
        "marketValue": "$3.89",
        "marketValueNumber": 3.89,
        "dayChange": "+$0.14",
        "dayChangePct": "+3.82%",
        "costBasis": "$1.94",
        "gain": "+$1.95",
        "gainNumber": 1.95,
        "gainPct": "+100.69%",
        "accountWeight": "0.09%",
        "averageCostBasis": "$80.83",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "GEV",
        "description": "GE VERNOVA INC COM",
        "quantity": "0.106",
        "price": "$1156.97",
        "priceChange": "+$43.86",
        "marketValue": "$122.63",
        "marketValueNumber": 122.63,
        "dayChange": "+$4.64",
        "dayChangePct": "+3.94%",
        "costBasis": "$99.77",
        "gain": "+$22.86",
        "gainNumber": 22.86,
        "gainPct": "+22.92%",
        "accountWeight": "2.94%",
        "averageCostBasis": "$941.23",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "GOOG",
        "description": "ALPHABET INC CAP STK CL C",
        "quantity": "0.371",
        "price": "$362.68",
        "priceChange": "+$6.50",
        "marketValue": "$134.55",
        "marketValueNumber": 134.55,
        "dayChange": "+$2.41",
        "dayChangePct": "+1.82%",
        "costBasis": "$114.95",
        "gain": "+$19.60",
        "gainNumber": 19.6,
        "gainPct": "+17.05%",
        "accountWeight": "3.23%",
        "averageCostBasis": "$309.84",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "GOOGL",
        "description": "ALPHABET INC CAP STK CL A",
        "quantity": "0.622",
        "price": "$365.25",
        "priceChange": "+$5.34",
        "marketValue": "$227.18",
        "marketValueNumber": 227.18,
        "dayChange": "+$3.32",
        "dayChangePct": "+1.48%",
        "costBasis": "$206.07",
        "gain": "+$21.11",
        "gainNumber": 21.11,
        "gainPct": "+10.24%",
        "accountWeight": "5.45%",
        "averageCostBasis": "$331.30",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "GTLB",
        "description": "GITLAB INC CLASS A COM",
        "quantity": "0.047",
        "price": "$32.625",
        "priceChange": "+$0.56",
        "marketValue": "$1.53",
        "marketValueNumber": 1.53,
        "dayChange": "+$0.02",
        "dayChangePct": "+1.73%",
        "costBasis": "$2.00",
        "gain": "-$0.47",
        "gainNumber": -0.47,
        "gainPct": "-23.34%",
        "accountWeight": "0.04%",
        "averageCostBasis": "$42.55",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "IBM",
        "description": "INTERNATIONAL BUS MACH CORP COM USD0.20",
        "quantity": "0.006",
        "price": "$298.76",
        "priceChange": "+$9.24",
        "marketValue": "$1.79",
        "marketValueNumber": 1.79,
        "dayChange": "+$0.05",
        "dayChangePct": "+3.19%",
        "costBasis": "$1.75",
        "gain": "+$0.04",
        "gainNumber": 0.04,
        "gainPct": "+2.43%",
        "accountWeight": "0.04%",
        "averageCostBasis": "$291.67",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "KMI",
        "description": "KINDER MORGAN INC COM USD0.01",
        "quantity": "0.073",
        "price": "$31.68",
        "priceChange": "-$0.38",
        "marketValue": "$2.31",
        "marketValueNumber": 2.31,
        "dayChange": "-$0.03",
        "dayChangePct": "-1.19%",
        "costBasis": "$1.97",
        "gain": "+$0.34",
        "gainNumber": 0.34,
        "gainPct": "+17.39%",
        "accountWeight": "0.06%",
        "averageCostBasis": "$26.99",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "LITE",
        "description": "LUMENTUM HLDGS INC COM",
        "quantity": "0.008",
        "price": "$728.84",
        "priceChange": "+$0.52",
        "marketValue": "$5.83",
        "marketValueNumber": 5.83,
        "dayChange": "+$0.00",
        "dayChangePct": "+0.07%",
        "costBasis": "$1.94",
        "gain": "+$3.89",
        "gainNumber": 3.89,
        "gainPct": "+200.55%",
        "accountWeight": "0.14%",
        "averageCostBasis": "$242.50",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "LNG",
        "description": "CHENIERE ENERGY INC COM USD0.003",
        "quantity": "0.009",
        "price": "$246.06",
        "priceChange": "+$0.09",
        "marketValue": "$2.21",
        "marketValueNumber": 2.21,
        "dayChange": "+$0.00",
        "dayChangePct": "+0.03%",
        "costBasis": "$1.93",
        "gain": "+$0.28",
        "gainNumber": 0.28,
        "gainPct": "+14.74%",
        "accountWeight": "0.05%",
        "averageCostBasis": "$214.44",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "MDB",
        "description": "MONGODB INC CL A",
        "quantity": "0.005",
        "price": "$352.07",
        "priceChange": "-$2.81",
        "marketValue": "$1.76",
        "marketValueNumber": 1.76,
        "dayChange": "-$0.02",
        "dayChangePct": "-0.80%",
        "costBasis": "$1.68",
        "gain": "+$0.08",
        "gainNumber": 0.08,
        "gainPct": "+4.78%",
        "accountWeight": "0.04%",
        "averageCostBasis": "$336.00",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "MLM",
        "description": "MARTIN MARIETTA MATERIALS INC COM USD0.01",
        "quantity": "0.003",
        "price": "$604.56",
        "priceChange": "+$5.14",
        "marketValue": "$1.81",
        "marketValueNumber": 1.81,
        "dayChange": "+$0.01",
        "dayChangePct": "+0.85%",
        "costBasis": "$1.78",
        "gain": "+$0.03",
        "gainNumber": 0.03,
        "gainPct": "+1.89%",
        "accountWeight": "0.04%",
        "averageCostBasis": "$593.33",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "MRVL",
        "description": "MARVELL TECHNOLOGY INC COM",
        "quantity": "0.024",
        "price": "$251.50",
        "priceChange": "+$6.21",
        "marketValue": "$6.03",
        "marketValueNumber": 6.03,
        "dayChange": "+$0.14",
        "dayChangePct": "+2.53%",
        "costBasis": "$1.93",
        "gain": "+$4.10",
        "gainNumber": 4.1,
        "gainPct": "+212.74%",
        "accountWeight": "0.14%",
        "averageCostBasis": "$80.42",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "MSFT",
        "description": "MICROSOFT CORP",
        "quantity": "0.012",
        "price": "$386.605",
        "priceChange": "-$3.88",
        "marketValue": "$4.63",
        "marketValueNumber": 4.63,
        "dayChange": "-$0.05",
        "dayChangePct": "-1.00%",
        "costBasis": "$5.92",
        "gain": "-$1.29",
        "gainNumber": -1.29,
        "gainPct": "-21.64%",
        "accountWeight": "0.11%",
        "averageCostBasis": "$493.33",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "MU",
        "description": "MICRON TECHNOLOGY INC",
        "quantity": "1",
        "price": "$989.49",
        "priceChange": "+$14.08",
        "marketValue": "$989.49",
        "marketValueNumber": 989.49,
        "dayChange": "+$14.08",
        "dayChangePct": "+1.44%",
        "costBasis": "$391.31",
        "gain": "+$598.18",
        "gainNumber": 598.18,
        "gainPct": "+152.86%",
        "accountWeight": "23.75%",
        "averageCostBasis": "$391.31",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "NEE",
        "description": "NEXTERA ENERGY INC COM USD0.01",
        "quantity": "0.023",
        "price": "$87.61",
        "priceChange": "-$0.73",
        "marketValue": "$2.01",
        "marketValueNumber": 2.01,
        "dayChange": "-$0.02",
        "dayChangePct": "-0.83%",
        "costBasis": "$1.98",
        "gain": "+$0.03",
        "gainNumber": 0.03,
        "gainPct": "+1.76%",
        "accountWeight": "0.05%",
        "averageCostBasis": "$86.09",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "NOW",
        "description": "SERVICENOW INC COM USD0.001",
        "quantity": "0.02",
        "price": "$108.36",
        "priceChange": "+$2.04",
        "marketValue": "$2.16",
        "marketValueNumber": 2.16,
        "dayChange": "+$0.04",
        "dayChangePct": "+1.91%",
        "costBasis": "$3.28",
        "gain": "-$1.12",
        "gainNumber": -1.12,
        "gainPct": "-33.93%",
        "accountWeight": "0.05%",
        "averageCostBasis": "$164.00",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "NVDA",
        "description": "NVIDIA CORPORATION COM",
        "quantity": "0.032",
        "price": "$196.26",
        "priceChange": "+$1.43",
        "marketValue": "$6.28",
        "marketValueNumber": 6.28,
        "dayChange": "+$0.04",
        "dayChangePct": "+0.73%",
        "costBasis": "$5.82",
        "gain": "+$0.46",
        "gainNumber": 0.46,
        "gainPct": "+7.90%",
        "accountWeight": "0.15%",
        "averageCostBasis": "$181.88",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "PANW",
        "description": "PALO ALTO NETWORKS INC COM USD0.0001",
        "quantity": "0.009",
        "price": "$353.80",
        "priceChange": "+$5.74",
        "marketValue": "$3.18",
        "marketValueNumber": 3.18,
        "dayChange": "+$0.05",
        "dayChangePct": "+1.64%",
        "costBasis": "$1.81",
        "gain": "+$1.37",
        "gainNumber": 1.37,
        "gainPct": "+75.92%",
        "accountWeight": "0.08%",
        "averageCostBasis": "$201.11",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "PLTR",
        "description": "PALANTIR TECHNOLOGIES INC CL A",
        "quantity": "3",
        "price": "$132.54",
        "priceChange": "+$3.24",
        "marketValue": "$397.62",
        "marketValueNumber": 397.62,
        "dayChange": "+$9.72",
        "dayChangePct": "+2.50%",
        "costBasis": "$456.71",
        "gain": "-$59.09",
        "gainNumber": -59.09,
        "gainPct": "-12.94%",
        "accountWeight": "9.54%",
        "averageCostBasis": "$152.24",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "ROK",
        "description": "ROCKWELL AUTOMATION INC COM USD1",
        "quantity": "0.005",
        "price": "$481.635",
        "priceChange": "+$9.94",
        "marketValue": "$2.40",
        "marketValueNumber": 2.4,
        "dayChange": "+$0.04",
        "dayChangePct": "+2.10%",
        "costBasis": "$1.84",
        "gain": "+$0.56",
        "gainNumber": 0.56,
        "gainPct": "+30.87%",
        "accountWeight": "0.06%",
        "averageCostBasis": "$368.00",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "SCCO",
        "description": "SOUTHERN COPPER CORP",
        "quantity": "0.031",
        "price": "$173.78",
        "priceChange": "+$1.77",
        "marketValue": "$5.38",
        "marketValueNumber": 5.38,
        "dayChange": "+$0.05",
        "dayChangePct": "+1.02%",
        "costBasis": "$3.90",
        "gain": "+$1.48",
        "gainNumber": 1.48,
        "gainPct": "+38.13%",
        "accountWeight": "0.13%",
        "averageCostBasis": "$125.81",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "SMCI",
        "description": "SUPER MICRO COMPUTER INC COM NEW",
        "quantity": "17.114",
        "price": "$26.86",
        "priceChange": "-$0.36",
        "marketValue": "$459.68",
        "marketValueNumber": 459.68,
        "dayChange": "-$6.17",
        "dayChangePct": "-1.33%",
        "costBasis": "$499.99",
        "gain": "-$40.31",
        "gainNumber": -40.31,
        "gainPct": "-8.07%",
        "accountWeight": "11.03%",
        "averageCostBasis": "$29.22",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "SMR",
        "description": "NUSCALE PWR CORP CL A COM",
        "quantity": "0.091",
        "price": "$9.641",
        "priceChange": "-$0.12",
        "marketValue": "$0.87",
        "marketValueNumber": 0.87,
        "dayChange": "-$0.02",
        "dayChangePct": "-1.22%",
        "costBasis": "$1.98",
        "gain": "-$1.11",
        "gainNumber": -1.11,
        "gainPct": "-55.70%",
        "accountWeight": "0.02%",
        "averageCostBasis": "$21.76",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "SNOW",
        "description": "SNOWFLAKE INC. COMMON STOCK",
        "quantity": "0.007",
        "price": "$260.5848",
        "priceChange": "+$0.43",
        "marketValue": "$1.82",
        "marketValueNumber": 1.82,
        "dayChange": "+$0.00",
        "dayChangePct": "+0.16%",
        "costBasis": "$1.76",
        "gain": "+$0.06",
        "gainNumber": 0.06,
        "gainPct": "+3.64%",
        "accountWeight": "0.04%",
        "averageCostBasis": "$251.43",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "SO",
        "description": "SOUTHERN CO",
        "quantity": "0.022",
        "price": "$96.25",
        "priceChange": "-$1.73",
        "marketValue": "$2.11",
        "marketValueNumber": 2.11,
        "dayChange": "-$0.04",
        "dayChangePct": "-1.77%",
        "costBasis": "$2.00",
        "gain": "+$0.11",
        "gainNumber": 0.11,
        "gainPct": "+5.87%",
        "accountWeight": "0.05%",
        "averageCostBasis": "$90.91",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "TSM",
        "description": "TAIWAN SEMICONDUCTOR MANUFACTURING SPON ADS EACH REP 5 ORD TWD10",
        "quantity": "0.007",
        "price": "$453.92",
        "priceChange": "+$19.76",
        "marketValue": "$3.17",
        "marketValueNumber": 3.17,
        "dayChange": "+$0.13",
        "dayChangePct": "+4.55%",
        "costBasis": "$1.93",
        "gain": "+$1.24",
        "gainNumber": 1.24,
        "gainPct": "+64.63%",
        "accountWeight": "0.08%",
        "averageCostBasis": "$275.71",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "TT",
        "description": "TRANE TECHNOLOGIES PLC COM USD1",
        "quantity": "0.004",
        "price": "$485.94",
        "priceChange": "+$7.81",
        "marketValue": "$1.94",
        "marketValueNumber": 1.94,
        "dayChange": "+$0.03",
        "dayChangePct": "+1.63%",
        "costBasis": "$1.64",
        "gain": "+$0.30",
        "gainNumber": 0.3,
        "gainPct": "+18.52%",
        "accountWeight": "0.05%",
        "averageCostBasis": "$410.00",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "UBER",
        "description": "UBER TECHNOLOGIES INC COM",
        "quantity": "1",
        "price": "$73.455",
        "priceChange": "-$0.97",
        "marketValue": "$73.45",
        "marketValueNumber": 73.45,
        "dayChange": "-$0.98",
        "dayChangePct": "-1.31%",
        "costBasis": "$84.76",
        "gain": "-$11.31",
        "gainNumber": -11.31,
        "gainPct": "-13.34%",
        "accountWeight": "1.76%",
        "averageCostBasis": "$84.76",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "VMC",
        "description": "VULCAN MATERIALS CO",
        "quantity": "0.007",
        "price": "$304.0601",
        "priceChange": "+$0.87",
        "marketValue": "$2.12",
        "marketValueNumber": 2.12,
        "dayChange": "+$0.00",
        "dayChangePct": "+0.28%",
        "costBasis": "$1.97",
        "gain": "+$0.15",
        "gainNumber": 0.15,
        "gainPct": "+8.04%",
        "accountWeight": "0.05%",
        "averageCostBasis": "$281.43",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "VRT",
        "description": "VERTIV HOLDINGS CO COM CL A",
        "quantity": "0.012",
        "price": "$320.22",
        "priceChange": "+$19.69",
        "marketValue": "$3.84",
        "marketValueNumber": 3.84,
        "dayChange": "+$0.23",
        "dayChangePct": "+6.55%",
        "costBasis": "$1.93",
        "gain": "+$1.91",
        "gainNumber": 1.91,
        "gainPct": "+99.10%",
        "accountWeight": "0.09%",
        "averageCostBasis": "$160.83",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "VTI",
        "description": "VANGUARD INDEX FDS VANGUARD TOTAL STK MKT ETF",
        "quantity": "0.545",
        "price": "$371.8201",
        "priceChange": "+$3.06",
        "marketValue": "$202.64",
        "marketValueNumber": 202.64,
        "dayChange": "+$1.66",
        "dayChangePct": "+0.82%",
        "costBasis": "$179.95",
        "gain": "+$22.69",
        "gainNumber": 22.69,
        "gainPct": "+12.61%",
        "accountWeight": "4.86%",
        "averageCostBasis": "$330.18",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "WDC",
        "description": "WESTERN DIGITAL CORP. COM",
        "quantity": "0.19",
        "price": "$573.31",
        "priceChange": "+$34.31",
        "marketValue": "$108.92",
        "marketValueNumber": 108.92,
        "dayChange": "+$6.51",
        "dayChangePct": "+6.36%",
        "costBasis": "$99.96",
        "gain": "+$8.96",
        "gainNumber": 8.96,
        "gainPct": "+8.97%",
        "accountWeight": "2.61%",
        "averageCostBasis": "$526.11",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "XEL",
        "description": "XCEL ENERGY INC COM USD2.5",
        "quantity": "0.024",
        "price": "$80.695",
        "priceChange": "-$1.26",
        "marketValue": "$1.93",
        "marketValueNumber": 1.93,
        "dayChange": "-$0.04",
        "dayChangePct": "-1.55%",
        "costBasis": "$1.94",
        "gain": "-$0.01",
        "gainNumber": -0.01,
        "gainPct": "-0.18%",
        "accountWeight": "0.05%",
        "averageCostBasis": "$80.83",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    },
    {
        "brokerage": "Fidelity",
        "accountName": "Individual",
        "symbol": "XYL",
        "description": "XYLEM INC COM USD0.01",
        "quantity": "0.014",
        "price": "$119.26",
        "priceChange": "+$1.14",
        "marketValue": "$1.66",
        "marketValueNumber": 1.66,
        "dayChange": "+$0.01",
        "dayChangePct": "+0.96%",
        "costBasis": "$1.95",
        "gain": "-$0.29",
        "gainNumber": -0.29,
        "gainPct": "-14.38%",
        "accountWeight": "0.04%",
        "averageCostBasis": "$139.29",
        "assetType": "Cash",
        "reinvest": "",
        "reinvestCapitalGains": ""
    }
];
